---
title: "R_programming_w2"
output: html_document
---

# week2
## control structures

### if-else
```{r}
if(x>3){
  y<-10
}else{
  y<-0
}x<-
```

```{r}
y<-if(x>3){
  10
}else{
  0
    }
```


### for loops
```{r}
x<-c("a","b","c","d")
for(i in 1:4) {
  print(x[i])
}

for(i in seq_along(x)) {
  print(x[i])
}

for (letter in x) {
  print(letter)
}

for(i in 1:4) print(x[i]) ## not recommend

## nested for loops
x<-matrix(1:6,2,3)
for(i in seq_len(nrow(x))) {
  for(j in seq_len(ncol(x))) {
    print(x[i,j])
  }
}
```

### while loop
```{r}
count<- 0
while(count< 10) {
  print(count)
  count<-count+1
}

z<-5
while(z>=3 && z<=10) {
  print(z)
  coin<-rbinom(1,1,0.5) # 二项分布
  
  if(coin==1) { ## random walk
    z<-z+1
  } else {
    z<-z-1
  }
}
```

### repeat, next, break
```{r}
for(i in 1:100) {
  if (i <= 20) {
    ##skip the first 20 iterations
    next
  } else {
    i=i+0.3
  }
}
```

*more note in function2.R*

## coding standard
- text editor
- indent your code (首行缩进)
- limit the width of your code
- limit the length of individual function

## dates and times
```{r}
x <- as.Date("1970-01-01")
```

### times in R
-PISIXct: a large integer
-POSIXlt: list 

-function
    -weekdays
    -months
    -quarters
```{r}
x <- Sys.time()
p <- as.POSIXlt(x)
names(unclass(p))
```

```{r}
datestring <- c("January 10, 2012 10:40","December 9, 2011 9:10")
x <- strptime(datestring, "%B %d, %Y %H:%M")
x
```

```{r}
x <- as.Date("2012-01-01")
y <- strptime("9 Jan 2011 11:34:21", "%d %b %Y %H:%M:%S")
x-y
x <- as.POSIXlt(x)
x-y
```

```{r}
x <- as.POSIXct("2012-10-25 01:00:00")
y <- as.POSIXct("2012-10-25 06:00:00", tz = "GMT") #tz=timezone
y-x
```